#!/bin/zsh

while true; do
    if [ "$( xset -q | sed -rn 's/.*LED mask.*(.)[[:xdigit:]]{3}$/\1/p' )" = "0" ]; then
        LAYOUT="US";
    else
        LAYOUT="RU";
    fi;

    let "ram=$(vmstat -s | grep "used m" | cut -c6-14)/1024"
    cpu="$(top -bn1 | awk '/Cpu/ { cpu = 100 - $8 "%" }; END   { print cpu }')"
    vol="$(amixer get Master | grep -o "...%.")"
    mute="$(amixer get Master | grep -Eo "(\[[o][n]\]|\[[o][f][f]\])")"
    time="$( date +"%T" )"
    brightness="$(cat /sys/class/backlight/amdgpu_bl0/brightness)/$(cat /sys/class/backlight/amdgpu_bl0/max_brightness)"

    if [ "$( acpi | cut -c12-14 )" = "Dis" ]; then
        chg="$( acpi | cut -c25-27 )";
    else
        chg="$( acpi | cut -c22-24 )";
    fi;

    xsetroot -name "brt: [ $brightness ] | top: [ $ram Mib | $cpu ] | chg: $chg | $LAYOUT | vol: $vol | $mute | $time"
    sleep 1s
done &
